version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - restore_cache:
          keys:
            - bower-cache-{{ checksum "bower.json" }}-{{ .Environment.CACHE_VERSION }}
      - restore_cache:
          keys:
            - pulp-output-cache-{{ checksum "bower.json" }}-{{ .Environment.CACHE_VERSION }}
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
      - run:
          name: Install dependencies
          command: >-
            cp package.json package.json.backup &&
            echo 'export PATH=$PWD/node_modules/.bin:$PATH' >> "$BASH_ENV" &&
            source "$BASH_ENV" &&
            if [[ ! -d node_modules ]]; then
                npm i
            fi &&
            if [[ ! -d bower_components ]]; then
                bower i;
            fi &&
            mv package.json.backup package.json
      - save_cache:
          key: bower-cache-{{ checksum "bower.json" }}-{{ .Environment.CACHE_VERSION }}
          paths:
            - bower_components
      - save_cache:
          key: npm-cache-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
          paths:
            - node_modules
      - run:
          name: Build dependencies only
          command: >-
            if [[ ! -d output ]]; then
                mkdir .fake &&
                pulp build -j 2 --src-path .fake &&
                rm -rf .fake;
            fi
      - save_cache:
          key: pulp-output-cache-{{ checksum "bower.json" }}-{{ .Environment.CACHE_VERSION }}
          paths:
            - output
      - run:
          name: Build (no tests available)
          command: pulp build -j 2
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-and-test
